// Generated by CoffeeScript 1.8.0
(function() {
  var reinc;

  reinc = require("./");

  switch (reinc.afterRestart()) {
    case 'na':
      console.log("" + process.pid + ": let me die !");
      reinc.restart();
      break;
    case 'restarted':
      console.log("" + process.pid + ": re-birth !");
  }

}).call(this);

//# sourceMappingURL=testreincarnate.js.map
